################
version: '3.8' #
services:      #
################
#
#
######################################
# - Web Panel     : 0.0.0.0/aapanel  #
# - Entry         : aapanel          #
# - Username      : aapanel          #
# - password      : aapanel123       #
# - root password : aapanel123       #
######################################
#
######################################
 Aapanel:                            #
  # -------------------------------- #
  # Release: fresh, lib, lnmp, lamp  #
  image: 'aapanel/aapanel:lib'       #
  container_name: 'aapanel'          #
  network_mode: 'bridge'             #
  # -------------------------------- #
  hostname: 'aapanel'                #
  domainname: 'lan.local'            #
  # -------------------------------- #
  volumes:                           #
   - 'vhost:/www/server/panel/vhost' #
   - 'data:/www/server/data'         #
   - 'www:/www/wwwroot'              #
  # -------------------------------- #
  ports:                             #
  # -------------------------------- #
  # WEB PANEL                        #
   - '8886:7800'                     #
  # -------------------------------- #
  # Apache2                          #
   - '443:443'                       #
   - '80:80'                         #
  # -------------------------------- #
  # PHPMyAdmin                       #
   - '888:888'                       #
  # -------------------------------- #
  # FTP                              #
   - '21:21'                         #
######################################
#
#
######################################
volumes:                             #
 # --------------------------------- #
 vhost:                              #
 # --------------------------------- #
 data:                               #
 # --------------------------------- #
 www:                                #
 # --------------------------------- #
######################################
