################
version: '3.8' #
services:      #
################
#
###################################################################
 adguardhome:                                                     #
  # ------------------------------------------------------------- #
  image: 'adguard/adguardhome'                                    #
  container_name: 'adguardhome'                                   #
  network_mode: 'bridge'                                          #
  restart: 'unless-stopped'                                       #
  # ------------------------------------------------------------- #
  hostname: 'adguardhome'                                         #
  # ------------------------------------------------------------- #
  environment:                                                    #
   TZ: 'Europe/Paris'                                             #
  # ------------------------------------------------------------- #
  volumes:                                                        #
   - '/etc/localtime:/etc/localtime:ro'                           #
   - 'adguardhome_conf:/opt/adguardhome/conf'                     #
   - 'adguardhome_work:/opt/adguardhome/work'                     #
  # ------------------------------------------------------------- #
  ports:                                                          #
   - '3000:3000'                                                  #
   - '53:53/udp'                                                  #
   - '53:53/tcp'                                                  #
   - '3272:80'                                                    #
  # ------------------------------------------------------------- #
  labels:                                                         #
   Cacher: 'Non'                                                  #
  # ------------------------------------------------------------- #
###################################################################
#
#
###################################################################
volumes:                                                          #
 # -------------------------------------------------------------- #
 adguardhome_conf:                                                #
  external: false                                                 #
 # -------------------------------------------------------------- #
 adguardhome_work:                                                #
  external: false                                                 #
 # -------------------------------------------------------------- #
###################################################################

#mkdir -p /etc/systemd/resolved.conf.d;
#echo "[Resolve]
#DNS=8.8.8.8
#DNSStubListener=no" > /etc/systemd/resolved.conf.d/adguardhome.conf;
#mv /etc/resolv.conf /etc/resolv.conf.backup;
#ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf;
#systemctl restart systemd-resolved;
