################
version: '3.8' #
services:      #
################
#
#
#####################################################################
 Adminer:                                                           #
  # --------------------------------------------------------------- #
  image: 'adminer'                                                  #
  container_name: 'adminer'                                         #
  network_mode: 'bridge'                                            #
  restart: 'unless-stopped'                                         #
  hostname: 'Adminer'                                               #
  # --------------------------------------------------------------- #
  external_links:                                                   #
   - 'mariadb:mariadb'                                              #
  # --------------------------------------------------------------- #
  environment:                                                      #
   ADMINER_DEFAULT_SERVER: 'mariadb'                                #
  # --------------------------------------------------------------- #
  ports:                                                            #
   - '644:8080'                                                     #
  # --------------------------------------------------------------- #
  labels:                                                           #
   Cacher: 'Non'                                                    #
  # --------------------------------------------------------------- #
#####################################################################
