################
version: '3.8' #
services:      #
################
#
#####################################################################
 Dozzle:                                                            #
  # --------------------------------------------------------------- #
  image: 'amir20/dozzle'                                            #
  container_name: 'dozzle'                                          #
  network_mode: 'bridge'                                            #
  restart: 'unless-stopped'                                         #
  # --------------------------------------------------------------- #
  hostname: 'Dozzle'                                                #
  # --------------------------------------------------------------- #
  volumes:                                                          #
   - '/var/run/docker.sock:/var/run/docker.sock'                    #
  # --------------------------------------------------------------- #
  ports:                                                            #
   - '1005:8080'                                                    #
  # --------------------------------------------------------------- #
  labels:                                                           #
   Cacher: 'Non'                                                    #
#####################################################################
