################
version: '3.8' #
services:      #
################
#
#####################################################################
 FileBrowser:                                                       #
  image: 'filebrowser/filebrowser'                                  #
  container_name: 'FileBrowser'                                     #
  network_mode: 'bridge'                                            #
  restart: 'unless-stopped'                                         #
  # --------------------------------------------------------------- #
  hostname: 'FileBrowser'                                           #
  # --------------------------------------------------------------- #
  ports:                                                            #
   - '1114:80'                                                      #
  # --------------------------------------------------------------- #
  volumes:                                                          #
   - 'FileBrowser:/srv'                                             #
  # --------------------------------------------------------------- #
  labels:                                                           #
   Cacher: 'Non'                                                    #
#####################################################################
#
#
#####################################################################
volumes:                                                            #
 FileBrowser:                                                       #
  external: false                                                   #
  # --------------------------------------------------------------- #
#####################################################################
