################
version: "3.9" #
services:      #
################
#
########################################################
 Flaresolverr:                                         #
  # -------------------------------------------------- #
  image: 'ghcr.io/flaresolverr/flaresolverr:latest'    #
  container_name: 'flaresolverr'                       #
  network_mode: 'bridge'                               #
  restart: 'unless-stopped'                            #
  # -------------------------------------------------- #
  hostname: 'flaresolverr'                             #
  # -------------------------------------------------- #
  dns:                                                 #
   - 8.8.8.8                                           #
  # -------------------------------------------------- #
  sysctls:                                             #
   net.ipv6.conf.all.disable_ipv6: 1                   #
  # -------------------------------------------------- #
  environment:                                         #
   LOG_LEVEL:       'info'                             #
   LOG_HTML:        'false'                            #
   CAPTCHA_SOLVER:  'none'                             #
   BROWSER_TIMEOUT: '2000'                             #
  # -------------------------------------------------- #
  ports:                                               #
   - '1115:8191'                                       #
  # -------------------------------------------------- #
  labels:                                              #
   Cacher: 'Non'                                       #
  # -------------------------------------------------- #
########################################################
