################
version: '3.8' #
services:      #
################
#
##############################################################
 FreshRSS:                                                   #
  # -------------------------------------------------------- #
  image: 'lscr.io/linuxserver/freshrss:latest'               #
  container_name: 'FreshRSS'                                 #
  network_mode: 'bridge'                                     #
  restart: 'unless-stopped'                                  #
  # -------------------------------------------------------- #
  hostname: 'FreshRSS'                                       #
  # -------------------------------------------------------- #
  environment:                                               #
   PUID: '0'                                                 #
   PGID: '0'                                                 #
   TZ: 'Etc/UTC'                                             #
  # -------------------------------------------------------- #
  ports:                                                     #
   - '1120:80'                                               #
  # -------------------------------------------------------- #
  volumes:                                                   #
   - 'Data:/config'                                          #
  # -------------------------------------------------------- #
  labels:                                                    #
   Cacher: 'Non'                                             #
   # ------------------------------------------------------- #
##############################################################
#
#
##############################################################
volumes:                                                     #
 # --------------------------------------------------------- #
 Data:                                                       #
  external: false                                            #
 # --------------------------------------------------------- #
                                                             #
##############################################################
