################
version: '3.9' #
services:      #
################
#
#################################################################
 Jellyseerr:                                                    #
  # ----------------------------------------------------------- #
  image: 'fallenbagel/jellyseerr'                               #
  container_name: 'Jellyseerr'                                  #
  network_mode: 'bridge'                                        #
  restart: 'unless-stopped'                                     #
  # ----------------------------------------------------------- #
  hostname: 'Jellyseerr'                                        #
  # ----------------------------------------------------------- #
  environment:                                                  #
   # ---------------------------------------------------------- #
   TZ:   'Europe/Paris'                                         #
   PUID: '0'                                                    #
   PGID: '0'                                                    #
   # ---------------------------------------------------------- #
   DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:jellyseerr'   #
   TP_THEME: 'nord'                                             #
   # ---------------------------------------------------------- #
   LOG_LEVEL:   'debug'                                         #
  # ----------------------------------------------------------- #
  volumes:                                                      #
   # ---------------------------------------------------------- #
   - 'Jellyseerr:/app/config'                                   #
  # ----------------------------------------------------------- #
  ports:                                                        #
   - '8098:5055'                                                #
  # ----------------------------------------------------------- #
  labels:                                                       #
   Cacher: 'Non'                                                #
  # ----------------------------------------------------------- #
#################################################################
#
#################################################################
volumes:                                                        #
 Jellyfin:                                                      #
  external: false                                               #
  # ----------------------------------------------------------- #
 Jellyseerr:                                                    #
  external: false                                               #
  # ----------------------------------------------------------- #
#################################################################
