################
version: '3.8' #
services:      #
################
#
#
#################################################################
 LibreOffice:                                                   #
  image: 'linuxserver/libreoffice:latest'                       #
  # ----------------------------------------------------------- #
  container_name: 'LibreOffice'                                 #
  hostname: 'LibreOffice'                                       #
  network_mode: 'bridge'                                        #
  # ----------------------------------------------------------- #
  restart: 'unless-stopped'                                     #
  # ----------------------------------------------------------- #
  environment:                                                  #
   # ---------------------------------------------------------- #
   TZ: 'etc/paris'                                              #
   PUID: '1000'                                                 #
   PGID: '1000'                                                 #
   LC_ALL: 'fr_FR.UTF-8'                                        #
   TITLE: 'LibreOffice'                                         #
   # ---------------------------------------------------------- #
   CUSTOM_PORT: '3000'                                          #
   CUSTOM_HTTPS_PORT: '3001'                                    #
  # ----------------------------------------------------------- #
   CUSTOM_USER: 'admin'                                         #
   PASSWORD: 'admin'                                            #
  # ----------------------------------------------------------- #
  volumes:                                                      #
   - '/home/marc/Documents:/config'                             #
  # ----------------------------------------------------------- #
  ports:                                                        #
   - '3000:3000'                                                #
   - '3001:3001'                                                #
  # ----------------------------------------------------------- #
#################################################################
#
#
#################################################################
volumes:                                                        #
 Data:                                                          #
#################################################################
