################
version: '3.7' #
services:      #
################
#
#
############################################################
# Creation de certificat SSL en LOCAL                      #
############################################################
 certificats:                                              #
  # ------------------------------------------------------ #
  image: 'vishnunair/docker-mkcert'                        #
  container_name: 'mkcert'                                 #
  network_mode: 'bridge'                                   #
  restart: 'unless-stopped'                                #
  # ------------------------------------------------------ #
  hostname: 'mkcert'                                       #
  # ------------------------------------------------------ #
  environment:                                             #
   domain: 'mondomain.local,mondomain2.local'              #
  # ------------------------------------------------------ #
  volumes:                                                 #
   - 'mkcert/:/root/.local/share/mkcert'                   #
  # ------------------------------------------------------ #
############################################################
#
############################################################
volumes:
 mkcert:
  external: false
############################################################


############################################################
# Nginx:                                                   #
# - rootCA.pem          :                                  #
# - rootCA-key.pem      :                                  #
# - mondomain.local.pem :                                  #
############################################################
