################
version: '3.8' #
services:      #
################
#
#####################################################################
 Mysql:                                                             #
  # --------------------------------------------------------------- #
  image: 'mysql'                                                    #
  container_name: 'MySQL'                                           #
  network_mode: 'bridge'                                            #
  restart: 'unless-stopped'                                         #
  # --------------------------------------------------------------- #
  hostname: 'mysql'                                                 #
  # --------------------------------------------------------------- #
  command: --default-authentication-plugin=mysql_native_password    #
  # --------------------------------------------------------------- #
  environment:                                                      #
   # -------------------------------------------------------------- #
   MYSQL_ROOT_PASSWORD: 'root'                                      #
   # -------------------------------------------------------------- #
   MYSQL_DATABASE: 'exemple'                                        #
   MYSQL_USER: 'myusername'                                         #
   MYSQL_PASSWORD: 'mypassword'                                     #
  # --------------------------------------------------------------- #
  ports:                                                            #
   - '3307:3306'                                                    #
  # --------------------------------------------------------------- #
  volumes:                                                          #
   - 'Data:/var/lib/mysql'                                          #
  # --------------------------------------------------------------- #
  labels:                                                           #
   Cacher: 'Non'                                                    #
  # --------------------------------------------------------------- #
#####################################################################
#
#
#####################################################################
volumes:                                                            #
 # ---------------------------------------------------------------- #
 Data:                                                              #
  external: false                                                   #
 # ---------------------------------------------------------------- #
#####################################################################
