################
version: '3.7' #
services:      #
################
#
###################################################################
# Email: admin@example.com | Password: changeme                   #
###################################################################
 NginxProxyManager:                                               #
  # ------------------------------------------------------------- #
  image: 'jc21/nginx-proxy-manager'                               #
  container_name: 'nginx'                                         #
  network_mode: 'bridge'                                          #
  restart: 'unless-stopped'                                       #
  # ------------------------------------------------------------- #
  hostname: 'nginxproxymanager'                                   #
  # ------------------------------------------------------------- #
  external_links:                                                 #
   - 'mariadb:db'                                                 #
  # ------------------------------------------------------------- #
  sysctls:                                                        #
   - net.ipv6.conf.all.disable_ipv6=1                             #
  # ------------------------------------------------------------- #
  environment:                                                    #
   # ------------------------------------------------------------ #
   TZ: 'EUROPE/PARIS'                                             #
   # ------------------------------------------------------------ #
   DB_MYSQL_HOST: 'db'                                            #
   DB_MYSQL_PORT: '3306'                                          #
   DB_MYSQL_NAME: 'default'                                       #
   DB_MYSQL_USER: 'myusername'                                    #
   DB_MYSQL_PASSWORD: 'mypassword'                                #
  # ------------------------------------------------------------- #
  volumes:                                                        #
   - 'nginx_config:/config'                                       #
   - 'nginx_certif:/etc/letsencrypt'                              #
   - 'nginx_data:/data'                                           #
  # ------------------------------------------------------------- #
  ports:                                                          #
   - '80:80'                                                      #
   - '81:81'                                                      #
   - '443:443'                                                    #
  # ------------------------------------------------------------- #
  labels:                                                         #
   Cacher: 'Non'                                                  #
  # ------------------------------------------------------------- #
###################################################################
#
#
###################################################################
volumes:                                                          #
 # -------------------------------------------------------------- #
 nginx_config:                                                    #
  external: false                                                 #
 # -------------------------------------------------------------- #
 nginx_certif:                                                    #
  external: false                                                 #
 # -------------------------------------------------------------- #
 nginx_data:                                                      #
  external: false                                                 #
 # -------------------------------------------------------------- #
###################################################################
