################
version: '3.9' #
services:      #
################
#
############################################################################################################################################
# su -m -c "/usr/share/php/passbolt/bin/cake passbolt purge_email_queue"
# su -m -c "/usr/share/php/passbolt/bin/cake passbolt register_user -u <EMAIL> -f <MYUSERNAME> -l <PRENOM> -r admin" -s /bin/sh www-data;
# su -m -c "/usr/share/php/passbolt/bin/cake passbolt recover_user --username teste74@hotmail.fr" -s /bin/sh www-data;
# http://passbolt.local
 passbolt:
  image: 'passbolt/passbolt:latest-ce'
  container_name: 'Coffre'
  restart: 'unless-stopped'
  hostname: 'passbolt'
  external_links:
   - 'mariadb:db'
  environment:
   APP_FULL_BASE_URL: 'https://XXXXX.ddns.net/'
   DATASOURCES_DEFAULT_HOST: "db"
   DATASOURCES_DEFAULT_USERNAME: 'passbolt'
   DATASOURCES_DEFAULT_PASSWORD: 'P4ssb0lt'
   DATASOURCES_DEFAULT_DATABASE: 'passbolt'
  volumes:
   - 'gpg_volume:/etc/passbolt/gpg'
   - 'jwt_volume:/etc/passbolt/jwt'
  command:
   [
    "/usr/bin/wait-for.sh",
    "-t",
    "0",
    "db:3306",
    "--",
    "/docker-entrypoint.sh",
   ]
  ports:
   - '8881:80'
   - '4543:443'
############################################################################################################################################
#
#
############################################################################################################################################
volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
############################################################################################################################################
