################
version: '3.8' #
services:      #
################
#
#
#####################################################################################################
# Database for Rommapp                                                                              #
 romm_mariadb:
  # ----------------------------------------------------------------------------------------------- #
  image: 'docker.io/library/mariadb:latest'
  container_name: 'romm_mariadb'
  restart: 'unless-stopped'
  network_mode: 'bridge'
  # ----------------------------------------------------------------------------------------------- #
  hostname: 'rommdb'
  # ----------------------------------------------------------------------------------------------- #
  environment:
   PUID: '0'
   PGID: '0'
   TZ: 'Europe/Paris'
   MYSQL_DATABASE: 'romm'
   MYSQL_USER: 'romm-user'
   MYSQL_PASSWORD: 'db-password'
   MYSQL_ROOT_PASSWORD: 'db-root'
  # ----------------------------------------------------------------------------------------------- #
  volumes:
   - 'romm_mariadb:/var/lib/mysql'
  # ----------------------------------------------------------------------------------------------- #

#####################################################################################################
#
#
#####################################################################################################
 Rommapp:
  # ----------------------------------------------------------------------------------------------- #
  image: 'docker.io/rommapp/romm:latest'
  container_name: 'romm'
  restart: 'unless-stopped'
  network_mode: 'bridge'
  # ----------------------------------------------------------------------------------------------- #
  hostname: 'Rommapp'
  # ----------------------------------------------------------------------------------------------- #
  depends_on:
   - 'romm_mariadb'
  # ----------------------------------------------------------------------------------------------- #
  links:
   - 'romm_mariadb:db'
  # ----------------------------------------------------------------------------------------------- #
  environment:
   # ----------------------------------------------------------------------------------------------- #
   DB_HOST: 'db'
   DB_PORT: '3306'
   DB_NAME: 'romm'
   DB_USER: 'romm-user'
   DB_PASSWD: 'db-password'
   # ----------------------------------------------------------------------------------------------- #
   # Username & Password
   ROMM_AUTH_USERNAME: 'marc'  # default: admin
   ROMM_AUTH_PASSWORD: 'admin' # default: admin
   # ----------------------------------------------------------------------------------------------- #
   # Generate a key with `openssl rand -hex 32`
   ROMM_AUTH_SECRET_KEY: '54534ebc9c1e00ebf2184270255637a7fc15ed3a7e93e3c0db768546e77fbd8b'         
   # ----------------------------------------------------------------------------------------------- #
   DISABLE_CSRF_PROTECTION: 'true'
   # ----------------------------------------------------------------------------------------------- #
   #IGDB_CLIENT_ID: 'ID-KEY'
   #IGDB_CLIENT_SECRET: 'API-key'
   # ----------------------------------------------------------------------------------------------- #
   #MOBYGAMES_API_KEY: 'moby_mOJ2QufhuLsNUZ13U3nIfaJCXpS'
   # ----------------------------------------------------------------------------------------------- #
  volumes:
    - 'romm_assets:/romm/assets'
    - 'romm_config:/romm/config'        # [Optional] Path where config is stored
    - 'romm_library:/romm/library'      # 
    - 'romm_logs:/romm/logs'            # [Optional] Path where logs are stored
    - 'romm_resources:/romm/resources'  # [Optional] Path where roms metadata (covers) are stored
    - 'romm_redis:/redis-data'
   # ----------------------------------------------------------------------------------------------- #
  ports:
   - '8060:8080'

#######################################################################################################
#
#
#######################################################################################################   
volumes:
 romm_mariadb:
 romm_assets:
 romm_config:
 romm_library:
 romm_logs:
 romm_redis:
 romm_resources:
#######################################################################################################
