################
version: '3.8' #
services:      #
################
#
#
################################################
 URBackup:
  # ------------------------------------------ #
  cap_add:
   - 'SYS_ADMIN'
  # ------------------------------------------ #
  image: 'uroni/urbackup-server'
  container_name: 'URBackup'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'URBackup'
  # ------------------------------------------ #
  environment:
   PUID: '0'
   GUID: '0'
   TZ: 'Europe/Paris'
  # ------------------------------------------ #
  volumes:
   - 'Backups:/backups'
   - 'URBackup:/var/urbackup'
  # ------------------------------------------ #
  ports:
   - '55413:55413'
   - '55414:55414' # WebUI
   - '55415:55415'
   - '35623:35623/udp'
  # ------------------------------------------ #
################################################
#
#
################################################
volumes:
 # ------------------------------------------ #
 Backups:
  external: false
 # ------------------------------------------ #
 URBackup:
  external: false
################################################

