################
version: '3.8' #
services:      #
################
#
###################################################################
# DATABASE: default | USER: myusername | PASS: mypassword         #
# Token: admin                                                    #
###################################################################
 bitwarden:                                                       #
  # ------------------------------------------------------------- #
  image: 'vaultwarden/server'                                     #
  container_name: 'bitwarden'                                     #
  network_mode: 'bridge'                                          #
  restart: 'unless-stopped'                                       #
  # ------------------------------------------------------------- #
  hostname: 'bitwarden'                                           #
  # ------------------------------------------------------------- #
  external_links:                                                 #
   - 'mariadb:db'                                                 #
  # ------------------------------------------------------------- #
  sysctls:                                                        #
   - net.ipv6.conf.all.disable_ipv6=1                             #
  # ------------------------------------------------------------- #
  environment:                                                    #
   # ------------------------------------------------------------ #
   TZ: 'Europe/Paris'                                             #
   PUID: '0'                                                      #
   PGID: '0'                                                      #
   # ------------------------------------------------------------ #
   # General                                                      #
   DOMAIN: 'http://localhost'                                     #
   SENDS_ALLOWED: 'true'                                          #
   HIBP_API_KEY: ''                                               #
   USER_ATTACHMENT_LIMIT: ''                                      #
   ORG_ATTACHMENT_LIMIT: ''                                       #
   USER_SEND_LIMIT: ''                                            #
   TRASH_AUTO_DELETE_DAYS: ''                                     #
   INCOMPLETE_2FA_TIME_LIMIT: '3'                                 #
   DISABLE_ICON_DOWNLOAD: 'false'                                 #
   SIGNUPS_ALLOWED: 'true'                                        #
   SIGNUPS_VERIFY: 'false'                                        #
   SIGNUPS_VERIFY_RESEND_TIME: '3600'                             #
   SIGNUPS_VERIFY_RESEND_LIMIT: '6'                               #
   SIGNUPS_DOMAINS_WHITELIST: ''                                  #
   ORG_CREATION_USERS: ''                                         #
   INVITATIONS_ALLOWED: 'true'                                    #
   EMERGENCY_ACCESS_ALLOWED: 'true'                               #
   EMAIL_CHANGE_ALLOWED: 'true'                                   #
   PASSWORD_ITERATIONS: '600000'                                  #
   PASSWORD_HINTS_ALLOWED: 'true'                                 #
   SHOW_PASSWORD_HINT: 'false'                                    #
   ADMIN_TOKEN: 'admin'                                           #
   INVITATION_ORG_NAME: 'Vaultwarden'                             #
  # ------------------------------------------------------------- #
   # Advanced                                                     #
   IP_HEADER: 'X-Real-IP'                                         #
   ICON_REDIRECT_CODE: '302'                                      #
   ICON_CACHE_TTL: '2592000'                                      #
   ICON_CACHE_NEGTTL: '259200'                                    #
   ICON_DOWNLOAD_TIMEOUT: '10'                                    #
   ICON_BLACKLIST_REGEX: ''                                       #
   ICON_BLACKLIST_NON_GLOBAL_IPS: 'true'                          #
   DISABLE_2FA_REMEMBER: 'false'                                  #
   AUTHENTICATOR_DISABLE_TIME_DRIFT: 'false'                      #
   REQUIRE_DEVICE_EMAIL: 'false'                                  #
   RELOAD_TEMPLATES: 'false'                                      #
   LOG_TIMESTAMP_FORMAT: '%Y-%m-%d %H:%M:%S.%3f'                  #
   ALLOWED_IFRAME_ANCESTORS: ''                                   #
   ADMIN_SESSION_LIFETIME: '60'                                   #
   # ------------------------------------------------------------ #
   # Yubikey                                                      #
   _ENABLE_YUBICO: 'false'                                        #
   YUBICO_CLIENT_ID: ''                                           #
   YUBICO_SECRET_KEY: ''                                          #
   YUBICO_SERVER: ''                                              #
   # ------------------------------------------------------------ #
   # Global Duo                                                   #
   _ENABLE_DUO: 'false'                                           #
   DUO_IKEY: ''                                                   #
   DUO_SKEY: ''                                                   #
   DUO_HOST: ''                                                   #
   # ------------------------------------------------------------ #
   # SMTP EMAIL                                                   #
   _ENABLE_SMTP: 'true'                                           #
   USE_SENDMAIL: 'false'                                          #
   SENDMAIL_COMMAND: ''                                           #
   SMTP_HOST: 'smtp.gmail.com'                                    #
   SMTP_SECURITY: 'starttls'                                      #
   SMTP_PORT: '587'                                               #
   SMTP_FROM: 'XXXXXXXXXXXX@gmail.com'                            #
   SMTP_FROM_NAME: 'XXXXXXXXXXXX@gmail.com'                       #
   #SMTP_FROM_NAME: '[VaultWarden] Mail de confirmation'          #
   SMTP_USERNAME: 'XXXXXXXXXXXX@gmail.com'                        #
   SMTP_PASSWORD: 'XXXXXXXXXXXXXXXX'                              #
   SMTP_AUTH_MECHANISM: 'Plain, Login, Xoauth2'                   #
   SMTP_TIMEOUT: '30'                                             #
   HELO_NAME: 'HELO'                                              #
   SMTP_EMBED_IMAGES: 'true'                                      #
   SMTP_ACCEPT_INVALID_CERTS: 'false'                             #
   SMTP_ACCEPT_INVALID_HOSTNAMES: 'false'                         #
   # ------------------------------------------------------------ #
   # EMAIL 2FA                                                    #
   _ENABLE_EMAIL_2FA: 'false'                                     #
   EMAIL_TOKEN_SIZE: '6'                                          #
   EMAIL_EXPIRATION_TIME: '900'                                   #
   EMAIL_ATTEMPTS_LIMIT: '3'                                      #
   # ------------------------------------------------------------ #
   # READ-ONLY CONFIG                                             #
   DATA_FOLDER: 'data'                                            #
   DATABASE_URL: 'mysql://myusername:mypassword@db:3306/default'  #
   ICON_CACHE_FOLDER: 'data/icon_cache'                           #
   ATTACHMENTS_FOLDER: 'data/attachments'                         #
   SENDS_FOLDER: 'data/sends'                                     #
   TMP_FOLDER: 'data/tmp'                                         #
   TEMPLATES_FOLDER: 'data/templates'                             #
   RSA_KEY_FILENAME: 'data/rsa_key'                               #
   WEB_VAULT_FOLDER: 'web-vault/'                                 #
   WEBSOCKET_ENABLED: 'false'                                     #
   WEBSOCKET_ADDRESS: '0.0.0.0'                                   #
   WEBSOCKET_PORT: '3012'                                         #
   PUSH_ENABLED: 'false'                                          #
   PUSH_RELAY_URL: 'https://push.bitwarden.com'                   #
   PUSH_IDENTITY_URL: 'https://identity.bitwarden.com'            #
   PUSH_INSTALLATION_ID: ''                                       #
   PUSH_INSTALLATION_KEY: ''                                      #
   JOB_POLL_INTERVAL_MS: '30000'                                  #
   SEND_PURGE_SCHEDULE: '0 5 * * * *'                             #
   TRASH_PURGE_SCHEDULE: '0 5 0 * * *'                            #
   INCOMPLETE_2DA_SCHEDULE: '30 * * * * *'                        #
  # ------------------------------------------------------------- #
  volumes:                                                        #
    - 'data:/data'                                                #
  # ------------------------------------------------------------- #
  ports:                                                          #
   - '7777:80'                                                    #
  # ------------------------------------------------------------- #
  labels:                                                         #
   Cacher: 'Non'                                                  #
  # ------------------------------------------------------------- #
###################################################################
#
###################################################################
volumes:                                                          #
 # -------------------------------------------------------------- #
 data:                                                            #
  external: false                                                 #
 # -------------------------------------------------------------- #
###################################################################
