################
version: '3.8' #
#######################################################
services:                                             #
#######################################################
 configure:                                           #
  # ------------------------------------------------- #
  image: "$TELEPORT_IMAGE"                            #
  container_name: 'teleport-configure'                #
  network_mode: 'bridge'                              #
  hostname: '192.168.0.80'                            #
  # ------------------------------------------------- #
  entrypoint: '/bin/sh'                               #
  command: -c "$COMMAND_START1"                       #
  # ------------------------------------------------- #
  volumes:                                            #
   - 'teleport_config:/etc/teleport'                  #
#######################################################
#
#
#######################################################
 teleport:                                            #
  # ------------------------------------------------- #
  image: "$TELEPORT_IMAGE"                            #
  container_name: 'teleport'                          #
  network_mode: 'bridge'                              #
  hostname: '192.168.0.80'                            #
  # ------------------------------------------------- #
  entrypoint: '/bin/sh'                               #
  command: -c "$COMMAND_START2"                       #
  # ------------------------------------------------- #
  volumes:                                            #
   - 'teleport_config:/etc/teleport'                  #
   - 'teleport_data:/var/lib/teleport'                #
  # ------------------------------------------------- #
  ports:                                              #
   - '3023:3023'                                      #
   - '3024:3024'                                      #
   - '3025:3025'                                      #
   - '5080:3080'                                      #
#######################################################
#
#
#######################################################
volumes:                                              #
 # -------------------------------------------------- #
 teleport_config:                                     #
  external: false                                     #
 # -------------------------------------------------- #
 teleport_data:                                       #
  external: false                                     #
#######################################################
