################
version: '3.8' #
services:      #
################
#
#
#######################################################
# Permet de generer le fichier de configuration       #
#######################################################
 configure:                                           #
  # ------------------------------------------------- #
  image: "$TELEPORT_IMAGE"                            #
  container_name: 'teleport-configure'                #
  network_mode: 'bridge'                              #
  hostname: '192.168.0.80'                            #
  # ------------------------------------------------- #
  entrypoint: '/bin/sh'                               #
  command: -c "$COMMAND_START1"                       #
  # ------------------------------------------------- #
  volumes:                                            #
   - 'config:/etc/teleport'                           #
#######################################################
#
#
#######################################################
 teleport:                                            #
  # ------------------------------------------------- #
  image: "$TELEPORT_IMAGE"                            #
  container_name: 'teleport'                          #
  network_mode: 'bridge'                              #
  hostname: '192.168.0.80'                            #
  # ------------------------------------------------- #
  entrypoint: '/bin/sh'                               #
  command: -c "$COMMAND_START2"                       #
  # ------------------------------------------------- #
  volumes:                                            #
   - 'config:/etc/teleport'                           #
   - 'data:/etc/teleport'                             #
  # ------------------------------------------------- #
  ports:                                              #
   - '3023:3023'                                      #
   - '3024:3024'                                      #
   - '3025:3025'                                      #
   - '5080:3080'                                      #
#######################################################
#
#
#######################################################
volumes:                                              #
 # -------------------------------------------------- #
 config:                                              #
  external: false                                     #
 # -------------------------------------------------- #
 data:                                                #
  external: false                                     #
#######################################################
