################
version: '3.8' #
services:      #
################
#
######################################
  AirSonic:
    image: 'linuxserver/airsonic'
    container_name: 'airsonic'
    network_mode: 'bridge'
    restart: 'unless-stopped'
    hostname: 'airsonic'
    domainname: 'labs'
    environment:
      PUID: ''
      PGID: ''
      TZ: 'Europe/Paris'
    ports:
      - '4040:4040' # WebUI
    volumes:
      - 'AirSonic:/config'
      - 'AirSonic:/media'
      - 'AirSonic:/playlists'
      - 'AirSonic:/podcasts'
######################################
volumes:
 AirSonic:
  external: false
######################################
