################
version: '3.8' #
services:      #
################
#
#
#############################################
 Cloud9:                                    #
  # --------------------------------------- #
  image: 'linuxserver/cloud9'               #
  container_name: 'cloud9'                  #
  network_mode: 'bridge'                    #
  restart: 'unless-stopped'                 #
  # --------------------------------------- #
  hostname: 'cloud9'                        #
  domainname: 'labs'                        #
  # --------------------------------------- #
  environment:                              #
   # -------------------------------------- #
   PUID: '0'                                #
   PGID: '0'                                #
   TZ: 'Europe/Paris'                       #
   USERNAME: 'admin'                        #
   PASSWORD: 'admin'                        #
  # --------------------------------------- #
  ports:                                    #
    - '8000:8000'                           #
  # --------------------------------------- #
  volumes:                                  #
    - 'Cloud9:/code'                        #
  # --------------------------------------- #
#############################################
#
#
#############################################
volumes:                                    #
 # ---------------------------------------- #
 Cloud9:                                    #
 # ---------------------------------------- #
#############################################
