version: '2.1'
services:
 Daapd:
  image: 'linuxserver/daapd'
  container_name: 'daapd'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'daapd'
  domainname: 'labs'
  environment:
   PUID: ''
   PGID: ''
    TZ: 'Europe/Paris'
  volumes:
   - 'Daapd:/config'
   - 'Daapd:/Podcasts'
   - 'Daapd:/Audiobooks'
   - 'Daapd:/Compilations'
  ports:
   - '3689:3689/tcp' # WebUI
   - '3689:3688'
volumes:
 Daapd:
  external: false
