version: '2.1'
services:
 Emby:
  image: 'linuxserver/emby'
  container_name: 'emby'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'emby'
  domainname: 'labs'
  environment:
   PUID: ''
   PGID: ''
   TZ: 'Europe/Paris'
  ports:
   - '8090:8096' # WebUI
  volumes:
   - 'Emby:/config'
   - 'Emby:/data/tvshows'

volumes:
 Emby:
  external: false
