################
version: '3.8' #
services:      #
################
#
########################################################
 Jackett:                                              #
  # -------------------------------------------------- #
  image: 'linuxserver/jackett'                         #
  container_name: 'jackett'                            #
  network_mode: 'bridge'                               #
  restart: 'unless-stopped'                            #
  # -------------------------------------------------- #
  hostname: 'jackett'                                  #
  # -------------------------------------------------- #
  dns:                                                 #
   - 8.8.8.8                                           #
  # -------------------------------------------------- #
  sysctls:                                             #
   net.ipv6.conf.all.disable_ipv6: 1                   #
  # -------------------------------------------------- #
  environment:                                         #
   # ------------------------------------------------- #
   TZ:   'Europe/Paris'                                #
   PUID: '0'                                           #
   PGID: '0'                                           #
   # ------------------------------------------------- #
   AUTO_UPDATE: 'true'                                 #
  # -------------------------------------------------- #
  volumes:                                             #
   - 'Jackett:/config'                                 #
  # -------------------------------------------------- #
  ports:                                               #
   - '1111:9117'                                       #
  # -------------------------------------------------- #
  labels:                                              #
   Cacher: 'Non'                                       #
  # -------------------------------------------------- #
########################################################
#
########################################################
volumes:                                               #
 # --------------------------------------------------- #
 Jackett:                                              #
  external: false                                      #
 # --------------------------------------------------- #
########################################################
