################
version: '3.8' #
services:      #
################
#
#################################################################
 Jellyfin:                                                      #
  # ----------------------------------------------------------- #
  image: 'linuxserver/jellyfin'                                 #
  container_name: 'Jellyfin'                                    #
  network_mode: 'bridge'                                        #
  restart: 'unless-stopped'                                     #
  hostname: 'Jellyfin'                                          #
  # ----------------------------------------------------------- #
  environment:                                                  #
   # ---------------------------------------------------------- #
   TZ: 'Europe/Paris'                                           #
   PUID: '0'                                                    #
   PGID: '0'                                                    #
   # ---------------------------------------------------------- #
   JELLYFIN_PublishedServerUrl: '0.0.0.0'                       #
   # ---------------------------------------------------------- #
   DOCKER_MODS: 'ghcr.io/gilbn/theme.park:jellyfin'             #
   TP_THEME: 'dracula'                                          #
  # ----------------------------------------------------------- #
  #devices:                                                     #
  #- '/dev/dri:/dev/dri'                                        #
  #- '/dev/video19:/dev/video19'                                #
  # ----------------------------------------------------------- #
  volumes:                                                      #
   # ---------------------------------------------------------- #
   - 'Jellyfin:/config'                                         #
  # ----------------------------------------------------------- #
  ports:                                                        #
   - '8096:8096'                                                #
  # ----------------------------------------------------------- #
  labels:                                                       #
   Cacher: 'Non'                                                #
#################################################################
#
#
#################################################################
volumes:                                                        #
  # ----------------------------------------------------------- #
 Jellyfin:                                                      #
  external: false                                               #
  # ----------------------------------------------------------- #
#################################################################
