################
version: '3.8' #
services:      #
################
#
#####################################################################
 MariaDB:                                                           #
  # --------------------------------------------------------------- #
  image: 'linuxserver/mariadb'                                      #
  container_name: 'mariadb'                                         #
  network_mode: 'bridge'                                            #
  restart: 'unless-stopped'                                         #
  # --------------------------------------------------------------- #
  hostname: 'mariadb'                                               #
  # --------------------------------------------------------------- #
  environment:                                                      #
   # -------------------------------------------------------------- #
   TZ: 'EUROPE/PARIS'                                               #
   # -------------------------------------------------------------- #
   PUID: '0'                                                        #
   PGID: '0'                                                        #
   # -------------------------------------------------------------- #
   MYSQL_ROOT_PASSWORD: 'root'                                      #
   MYSQL_DATABASE: 'default'                                        #
   MYSQL_USER: 'myusername'                                         #
   MYSQL_PASSWORD: 'mypassword'                                     #
   # -------------------------------------------------------------- #
  ports:                                                            #
   - '3306:3306'                                                    #
  # --------------------------------------------------------------- #
  volumes:                                                          #
   - 'Data:/config'                                                 #
  # --------------------------------------------------------------- #
  labels:                                                           #
   Cacher: 'Non'                                                    #
  # --------------------------------------------------------------- #
#####################################################################
#
#####################################################################
volumes:                                                            #
 # ---------------------------------------------------------------- #
 Data:                                                              #
  external: false                                                   #
 # ---------------------------------------------------------------- #
#####################################################################
