################
version: '3.8' #
services:      #
################
#
########################################################
  container_name: 'Prowlarr'                           #
  network_mode: 'bridge'                               #
  restart: 'unless-stopped'                            #
  # -------------------------------------------------- #
  hostname: 'Prowlarr'                                 #
  # -------------------------------------------------- #
  dns:                                                 #
   - 8.8.8.8                                           #
  # -------------------------------------------------- #
  environment:                                         #
   # ------------------------------------------------- #
   TZ:   'Europe/Paris'                                #
   PUID: '0'                                           #
   PGID: '0'                                           #
   # ------------------------------------------------- #
   DOCKER_MODS: 'ghcr.io/gilbn/theme.park:prowlarr'    #
   TP_THEME:    'dracula'                              #
  # -------------------------------------------------- #
  volumes:                                             #
   # ------------------------------------------------- #
   - 'Prowlarr:/config'                                #
   # ------------------------------------------------- #
  ports:                                               #
   - '9696:9696'                                       #
  # -------------------------------------------------- #
  labels:                                              #
   Cacher: 'Non'                                       #
  # -------------------------------------------------- #
########################################################
#
#
########################################################
volumes:                                               #
 Prowlarr:                                             #
  external: false                                      #
########################################################

