################
version: '3.8' #
services:      #
################
#
########################################################
 qbittorrent:                                          #
  # -------------------------------------------------- #
  image: 'linuxserver/qbittorrent:libtorrentv1'        #
  container_name: 'qbittorrent'                        #
  network_mode: 'bridge'                               #
  restart: 'unless-stopped'                            #
  # -------------------------------------------------- #
  hostname: 'qbittorrent'                              #
  # -------------------------------------------------- #
  dns:                                                 #
   - 8.8.8.8                                           #
  # -------------------------------------------------- #
  environment:                                         #
   # ------------------------------------------------- #
   TZ:   'Europe/Paris'                                #
   PUID: '0'                                           #
   PGID: '0'                                           #
   # ------------------------------------------------- #
   WEBUI_PORT: '1007'                                  #
  # -------------------------------------------------- #
  volumes:                                             #
   # ------------------------------------------------- #
   - 'Qbittorrent:/config'                             #
  # -------------------------------------------------- #
  ports:                                               #
   - '6881:6881'                                       #
   - '1110:1007'                                       #
  # -------------------------------------------------- #
  labels:                                              #
   Cacher: 'Non'                                       #
  # -------------------------------------------------- #
########################################################
#
########################################################
volumes:                                               #
 Qbittorrent:                                          #
  external: false                                      #
########################################################
