
################
version: '3.8' #
services:      #
################
#
########################################################
 Radarr:                                               #
  # -------------------------------------------------- #
  image: 'linuxserver/radarr:nightly'                  #
  container_name: 'radarr'                             #
  network_mode: 'bridge'                               #
  restart: 'unless-stopped'                            #
  # -------------------------------------------------- #
  hostname: 'radarr'                                   #
  # -------------------------------------------------- #
  environment:                                         #
   # ------------------------------------------------- #
   TZ:   'Europe/Paris'                                #
   PUID: '0'                                           #
   PGID: '0'                                           #
   # ------------------------------------------------- #
  volumes:                                             #
   # ------------------------------------------------- #
   - 'Radarr:/config'                                  #
  # -------------------------------------------------- #
  ports:                                               #
   - '1112:7878'                                       #
  # -------------------------------------------------- #
  labels:                                              #
   Cacher: 'Non'                                       #
  # -------------------------------------------------- #
########################################################
#
########################################################
volumes:                                               #
 Radarr:                                               #
  external: false                                      #
########################################################
