------------------------------------------------------------------------------------------------------------------------------------------------------------------------

![alttext](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png?v=4&s=4000)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## I. Présentation

```
GID     : ID du groupe qui lance le conteneur
USERID  : ID de l'utilisateur qui lance le conteneur
Volumes : /var/lib/docker/volumes
```
<br />
